/* Auto-generated by genmsg_cpp for file /home/luca/Projects/MarkerBasedNavigation/mbn_msgs/msg/MarkersIDs.msg */
#ifndef MBN_MSGS_MESSAGE_MARKERSIDS_H
#define MBN_MSGS_MESSAGE_MARKERSIDS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace mbn_msgs
{
template <class ContainerAllocator>
struct MarkersIDs_ {
  typedef MarkersIDs_<ContainerAllocator> Type;

  MarkersIDs_()
  : header()
  , markersIDs()
  {
  }

  MarkersIDs_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , markersIDs(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _markersIDs_type;
  std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  markersIDs;


  ROS_DEPRECATED uint32_t get_markersIDs_size() const { return (uint32_t)markersIDs.size(); }
  ROS_DEPRECATED void set_markersIDs_size(uint32_t size) { markersIDs.resize((size_t)size); }
  ROS_DEPRECATED void get_markersIDs_vec(std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other > & vec) const { vec = this->markersIDs; }
  ROS_DEPRECATED void set_markersIDs_vec(const std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other > & vec) { this->markersIDs = vec; }
private:
  static const char* __s_getDataType_() { return "mbn_msgs/MarkersIDs"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "26fde87b102132c5657ff6a5551efbfb"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
int32[]  markersIDs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, markersIDs);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, markersIDs);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(markersIDs);
    return size;
  }

  typedef boost::shared_ptr< ::mbn_msgs::MarkersIDs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mbn_msgs::MarkersIDs_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct MarkersIDs
typedef  ::mbn_msgs::MarkersIDs_<std::allocator<void> > MarkersIDs;

typedef boost::shared_ptr< ::mbn_msgs::MarkersIDs> MarkersIDsPtr;
typedef boost::shared_ptr< ::mbn_msgs::MarkersIDs const> MarkersIDsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::mbn_msgs::MarkersIDs_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::mbn_msgs::MarkersIDs_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace mbn_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::mbn_msgs::MarkersIDs_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::mbn_msgs::MarkersIDs_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::mbn_msgs::MarkersIDs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "26fde87b102132c5657ff6a5551efbfb";
  }

  static const char* value(const  ::mbn_msgs::MarkersIDs_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x26fde87b102132c5ULL;
  static const uint64_t static_value2 = 0x657ff6a5551efbfbULL;
};

template<class ContainerAllocator>
struct DataType< ::mbn_msgs::MarkersIDs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "mbn_msgs/MarkersIDs";
  }

  static const char* value(const  ::mbn_msgs::MarkersIDs_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::mbn_msgs::MarkersIDs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int32[]  markersIDs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::mbn_msgs::MarkersIDs_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::mbn_msgs::MarkersIDs_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::mbn_msgs::MarkersIDs_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::mbn_msgs::MarkersIDs_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.markersIDs);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MarkersIDs_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mbn_msgs::MarkersIDs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::mbn_msgs::MarkersIDs_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "markersIDs[]" << std::endl;
    for (size_t i = 0; i < v.markersIDs.size(); ++i)
    {
      s << indent << "  markersIDs[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.markersIDs[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // MBN_MSGS_MESSAGE_MARKERSIDS_H

